### ISSUE TITLE
`installv3.sh -trim` does not work

### ISSUE THREAD

**Issue by julianoes** [ATLFlight/cross_toolchain#11]
It seems that the `-trim` option for installv3.sh does not work anymore.

See the output [here](http://pastebin.com/W1d2TpAr).

@mcharleb FYI

**Comment by mcharleb** [comment]
@julianoes Where are we with this? Is trim still broken? I thought I fixed the missing libs that were previously trimmed. Is this blocking CI with Snapdragon Flight?

**Comment by julianoes** [comment]
@mcharleb just tried to build the Dockerfile with `-trim` and got:

```
Trimming HEXAGON_SDK_ROOT ...
find: '/home/docker1000/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf': No such file or directory
Usage: strip <option(s)> in-file(s)
 Removes symbols and sections from files
```

**Comment by mcharleb** [comment]
@julianoes I think Jim reverted the gcc version to the archive version. I'll make sure the installer script is still compatible, thanks.

**Comment by mcharleb** [comment]
@julianoes I spent all day fixing this and the DockerfileSnapdragon

Intrinsyc changed the name of the qrlSDK file and changed the format from zip to tgz. That affected the DockerfileSnapdragon and the installv3.sh and qrlinux_sysroot.sh scripts.

There is opportunity to prune the qrlSDK since it is installing a bunch of ARM executables that are not required in the sysroot.

Also fixed a bug in installv3.sh introduced in the reversion to the archive version of GCC.

See https://github.com/PX4/containers/pull/41 and https://github.com/ATLFlight/cross_toolchain/commit/a894d0e2104bab59d694cce3ef08206acaac76a1 @jywilson

**Comment by jywilson** [comment]
Many thanks Julian for doing this!

**Comment by julianoes** [comment]
@mcharleb thanks, this is fixed.
