### ISSUE TITLE
JRE libraries are missing or not compatible

### ISSUE THREAD

**Issue by 5yler** [ATLFlight/cross_toolchain#18]
I followed the instructions in the README and downloaded `Flight_3.1.3_qrlSDK.tgz` and `qualcomm_hexagon_sdk_lnx_3_0_eval.bin` to the `downloads` folder. I get the following output with `installsdk.sh`:

```bash
$ ./installsdk.sh --APQ8074 --trim --arm-gcc --qrlSDK

HEXAGON_INSTALL_HOME [/home/syler] 
Using the following for installation:
HEXAGON_SDK_ROOT=/home/syler/Qualcomm/Hexagon_SDK/3.0
HEXAGON_TOOLS_ROOT=/home/syler/Qualcomm/HEXAGON_Tools/7.2.12/Tools
Hexagon SDK not previously installed

Installing HEXAGON_SDK to /home/syler/Qualcomm/Hexagon_SDK/3.0
This will take a long time.
JRE libraries are missing or not compatible....
Exiting....
Verifying required tools were installed...
Failed to setup Hexagon SDK
```
I have installed `openjdk-8-jdk` and `openjdk-8-jre` using apt. Is there a specific JRE version required for the install? Please advise.

**Comment by 5yler** [comment]
Actually I was trying to set it up on an i686 Ubuntu machine, not x86_64 as specified in the [DevEnv setup docs](https://github.com/ATLFlight/ATLFlightDocs/blob/master/DevEnvSetup.md). I assume that's the problem.

**Comment by mcharleb** [comment]
I believe its been tested on Ubuntu 14.04 with openjdk-7-jre

On Nov 21, 2017 1:17 PM, "5yler" <notifications@github.com> wrote:

I followed the instructions in the README and downloaded
Flight_3.1.3_qrlSDK.tgz and qualcomm_hexagon_sdk_lnx_3_0_eval.bin to the
downloads folder. I get the following output with installsdk.sh:

$ ./installsdk.sh --APQ8074 --trim --arm-gcc --qrlSDK

HEXAGON_INSTALL_HOME [/home/syler]
Using the following for installation:
HEXAGON_SDK_ROOT=/home/syler/Qualcomm/Hexagon_SDK/3.0
HEXAGON_TOOLS_ROOT=/home/syler/Qualcomm/HEXAGON_Tools/7.2.12/Tools
Hexagon SDK not previously installed

Installing HEXAGON_SDK to /home/syler/Qualcomm/Hexagon_SDK/3.0
This will take a long time.
JRE libraries are missing or not compatible....
Exiting....
Verifying required tools were installed...
Failed to setup Hexagon SDK

I have installed openjdk-8-jdk and openjdk-8-jre using apt. Is there a
specific JRE version required for the install? Please advise.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ATLFlight/cross_toolchain/issues/18>, or mute the thread
